#!/usr/bin/env python3
"""Checker for documentation generated by documake.

Usage: check_docs.py <repo-root> [--docs docs] [--lang es|en|<code>] [--mermaid] [--json]
       check_docs.py <repo-root> --audit README.md CLAUDE.md ...   (drift in pre-existing docs)

Checks that what is written is true (paths and symbols exist) and that it
follows the constitution (no line numbers, complete module cards, no builder
perspective). Language defaults to _meta/documake.json "language", else "es".
Exits 1 on errors.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unicodedata

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from scan import list_files  # noqa: E402

LANG_PACKS = {
    "es": {
        "required": [
            "README.md", "01-stack-y-repositorio.md", "02-estructura.md", "03-vision-general.md",
            "04-mapa-del-codigo.md", "05-arquitectura.md", "09-recetas-de-cambio.md",
            "10-entorno-y-pruebas.md", "12-trampas-y-riesgos.md", "glosario.md", "_meta/cobertura.md",
        ],
        "modules_dir": "08-modulos/",
        "flows_dir": "07-flujos/",
        "tutorial_doc": "00-primer-cambio.md",
        "howto_section": "Cómo modificarlo",
        "flow_change_section": "Para cambiar este flujo",
        "crossref_re": r"\((?:ver|véase|vease|consultar)\s+[^)]{2,40}\)",
        "group_labels": ["Flujos", "Módulos", "Modulos", "Recetas"],
        "stack_doc": "01-stack-y-repositorio.md",
        "stack_sections": ["Stack", "Tipo de repositorio", "Organización del repositorio",
                           "Relación con otros repositorios"],
        "structure_doc": "02-estructura.md",
        "data_doc": "06-datos.md",
        "data_sections": ["Mapa de relaciones", "Resto de tablas"],
        "logical_words": ["lógica", "logica", "M:N", "via"],
        "module_sections": ["Responsabilidad", "Quién lo usa", "Invariantes", "Cómo modificarlo", "Cómo probarlo"],
        "markers": ["PENDIENTE", "PREGUNTAR", "NO VERIFICADO"],
        "readme_doc": "README.md",
        "quickstart_section": "Ruta feliz (Quickstart)",
        "recipes_doc": "09-recetas-de-cambio.md",
        "env_doc": "10-entorno-y-pruebas.md",
        "config_section": "Configuración",
        "ops_doc": "13-operacion-y-datos.md",
        "ops_sections": ["Docker", "Datos fuera de git", "Backups", "Logs y observabilidad"],
        "phrases": [
            r"\bdecidimos\b", r"\boptamos por\b", r"\belegimos\b", r"\binicialmente\b",
            r"\bal principio\b", r"\boriginalmente\b", r"\ben su momento\b", r"\bcomo todos saben\b",
            r"\bobviamente\b", r"\bsimplemente\b", r"\btrivial(mente)?\b", r"\bnuestr[oa]s?\b",
            r"\bnosotros\b", r"\bhicimos\b", r"\bmigramos\b", r"\bmás adelante\b", r"\ben el futuro\b",
            r"\belegante\b", r"\brobust[oa]\b", r"\bescalable\b", r"\blimpi[oa] y\b",
            r"\bverificad[oa] (con|por) grep\b", r"\bprueba del recién llegado\b",
            r"\bsubagente\b", r"\bauditoría de (la )?generación\b",
        ],
    },
    "en": {
        "required": [
            "README.md", "01-stack-and-repository.md", "02-structure.md", "03-overview.md",
            "04-code-map.md", "05-architecture.md", "09-change-recipes.md",
            "10-environment-and-testing.md", "12-pitfalls-and-risks.md", "glossary.md", "_meta/coverage.md",
        ],
        "modules_dir": "08-modules/",
        "flows_dir": "07-flows/",
        "tutorial_doc": "00-first-change.md",
        "howto_section": "How to modify it",
        "flow_change_section": "To change this flow",
        "crossref_re": r"\((?:see|cf\.?)\s+[^)]{2,40}\)",
        "group_labels": ["Flows", "Modules", "Recipes"],
        "stack_doc": "01-stack-and-repository.md",
        "stack_sections": ["Stack", "Repository type", "Repository organization",
                           "Relationship with other repositories"],
        "structure_doc": "02-structure.md",
        "data_doc": "06-data.md",
        "data_sections": ["Relationship map", "Other tables"],
        "logical_words": ["logical", "M:N", "via"],
        "module_sections": ["Responsibility", "Who uses it", "Invariants", "How to modify it", "How to test it"],
        "markers": ["TODO", "ASK", "UNVERIFIED"],
        "readme_doc": "README.md",
        "quickstart_section": "Quickstart",
        "recipes_doc": "09-change-recipes.md",
        "env_doc": "10-environment-and-testing.md",
        "config_section": "Configuration",
        "ops_doc": "13-operations-and-data.md",
        "ops_sections": ["Docker", "Data outside git", "Backups", "Logs and observability"],
        "phrases": [
            r"\bwe (decided|chose|opted|built|migrated|went)\b", r"\binitially\b", r"\boriginally\b",
            r"\bat first\b", r"\bback then\b", r"\bobviously\b", r"\bsimply\b", r"\bjust\b",
            r"\bour\b", r"\bwe\b", r"\bI (decided|chose|built)\b", r"\bas everyone knows\b",
            r"\btrivial(ly)?\b", r"\bin the future\b", r"\beventually\b", r"\belegant\b",
            r"\brobust\b", r"\bscalable\b", r"\bclean and\b",
            r"\bverified (with|by) grep\b", r"\bnewcomer test\b", r"\bsubagent\b",
            r"\bgeneration audit\b",
        ],
    },
}
MERMAID_TYPES = (
    "flowchart", "graph", "sequencediagram", "classdiagram", "statediagram", "erdiagram",
    "gantt", "journey", "pie", "mindmap", "timeline", "gitgraph", "c4context", "c4container",
    "c4component", "quadrantchart", "requirementdiagram", "block-beta", "architecture-beta",
    "sankey-beta", "xychart-beta",
)
LINE_REF_RE = re.compile(
    r"\b[\w./-]+\.[A-Za-z]{1,6}:\d+(-\d+)?\b|#L\d+|\blínea \d+\b|\bline \d+\b|\blinha \d+\b|\bligne \d+\b",
    re.I,
)
LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)\)")
INLINE_RE = re.compile(r"`([^`\n]+)`")
FENCE_RE = re.compile(r"^(\s*)(```+|~~~+)\s*([\w-]*)")
IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
PATH_EXT_RE = re.compile(r"^[\w.@/-]+\.[A-Za-z0-9]{1,8}/?$")
MANIFEST_EXT = {".json", ".yml", ".yaml", ".toml", ".lock", ".xml", ".gradle", ".cfg", ".mod"}
DOMAIN_RE = re.compile(r"^[\w-]+(\.[\w-]+)*\.(com|org|net|io|dev|app|es|cr|co|ai|me|info|biz)$", re.I)
SYMBOL_RE = re.compile(r"^[A-Za-z_]\w*(\s*(\.|::|#|->)\s*[A-Za-z_]\w*)*(\(\))?$")


def norm(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower()
    return re.sub(r"[^a-z0-9 ]", "", s).strip()


def load_pack(docs_dir, lang_arg):
    """Resolve language pack: --lang > documake.json > 'es'. documake.json 'structure' overrides."""
    meta = {}
    meta_path = os.path.join(docs_dir, "_meta", "documake.json")
    if os.path.isfile(meta_path):
        try:
            meta = json.load(open(meta_path, encoding="utf-8"))
        except (OSError, ValueError):
            meta = {}
    lang = lang_arg or meta.get("language") or "es"
    pack = dict(LANG_PACKS.get(lang, {}))
    pack.update(meta.get("structure") or {})
    missing = [k for k in ("required", "modules_dir", "flows_dir", "module_sections") if k not in pack]
    return lang, pack, missing, meta


def build_index(root, docs_dir):
    files, _ = list_files(root)
    paths, dirs, idents, corpus = set(), set(), set(), []
    docs_prefix = os.path.relpath(docs_dir, root).rstrip("/") + "/"
    for f in files:
        paths.add(f)
        parts = f.split("/")
        for i in range(1, len(parts)):
            dirs.add("/".join(parts[:i]))
        if f.startswith(docs_prefix):
            continue
        full = os.path.join(root, f)
        try:
            if os.path.getsize(full) > 1_500_000:
                continue
            with open(full, "rb") as fh:
                data = fh.read()
        except OSError:
            continue
        if b"\0" in data[:8192]:
            continue
        txt = data.decode("utf-8", "ignore")
        idents.update(IDENT_RE.findall(txt))
        idents.add(os.path.splitext(os.path.basename(f))[0])
        if os.path.splitext(f)[1].lower() in MANIFEST_EXT or os.path.basename(f) in ("Dockerfile", "Makefile"):
            corpus.append(txt)
    return paths, dirs, idents, "\n".join(corpus)


def split_md(text):
    """Return (prose lines with number, code blocks [(lang, content, start line)])."""
    prose, blocks = [], []
    in_block, fence, lang, buf, start = False, "", "", [], 0
    for i, line in enumerate(text.splitlines(), 1):
        m = FENCE_RE.match(line)
        if not in_block and m:
            in_block, fence, lang, buf, start = True, m.group(2)[:3], m.group(3).lower(), [], i
            continue
        if in_block and line.strip().startswith(fence):
            blocks.append((lang, "\n".join(buf), start))
            in_block = False
            continue
        if in_block:
            buf.append(line)
        else:
            prose.append((i, line))
    return prose, blocks


def classify(tok):
    t = tok.strip().rstrip(":,.;")
    if not t or " " in t or t.startswith(("http", "-", "~", "$", "<", "{", "/")) or "*" in t or "@" in t:
        return None, t
    if DOMAIN_RE.match(t) or os.path.basename(t.rstrip("/")).startswith(".env"):
        return None, t
    if "<" in t or ">" in t or "=" in t or re.search(r":\d+(-\d+)?$", t):
        return None, t
    if "/" in t or PATH_EXT_RE.match(t):
        if re.match(r"^\d", t) or t.count("/") == 0 and not PATH_EXT_RE.match(t):
            return None, t
        return "path", t
    if SYMBOL_RE.match(t):
        core = t[:-2] if t.endswith("()") else t
        looks_code = (
            t.endswith("()") or "_" in core or re.search(r"(\.|::|#|->)", core)
            or re.search(r"[a-z][A-Z]", core) or re.match(r"^[A-Z][a-z]+[A-Z]", core)
            or re.match(r"^[A-Z][A-Z0-9_]{2,}$", core)
        )
        if looks_code and len(core) >= 3:
            return "symbol", core
    return None, t


def mermaid_nodes(src):
    lines = [l.strip() for l in src.splitlines() if l.strip() and not l.strip().startswith("%%")]
    if not lines:
        return 0
    kind = lines[0].split()[0].lower()
    nodes = set()
    if kind in ("flowchart", "graph"):
        for l in lines[1:]:
            if l.startswith(("subgraph", "end", "classDef", "class ", "style", "linkStyle", "click")):
                continue
            for m in re.finditer(r"(?:^|[\s&>|-])([A-Za-z_][\w]*)\s*(?=[\[\(\{>]|\s*[-=.]{2,}|\s*&|\s*$)", l):
                nodes.add(m.group(1))
    elif kind == "sequencediagram":
        for l in lines[1:]:
            m = re.match(r"(participant|actor)\s+(\S+)", l)
            if m:
                nodes.add(m.group(2))
            for m in re.finditer(r"^([\w ]+?)\s*-{1,2}[>x)]{1,2}[+-]?\s*([\w ]+?)\s*:", l):
                nodes.update({m.group(1).strip(), m.group(2).strip()})
    elif kind == "erdiagram":
        for l in lines[1:]:
            m = re.match(r"([\w-]+)\s+[|}o{.-]+\s+([\w-]+)", l) or re.match(r"([\w-]+)\s*\{", l)
            if m:
                nodes.update(g for g in m.groups() if g)
    return len(nodes)


ER_REL = re.compile(r'^\s*("[^"]+"|[\w.\-]+)\s+([|}o{]{1,2}(?:--|\.\.)[|}o{]{1,2})\s+("[^"]+"|[\w.\-]+)\s*:\s*(.*)$')
ER_ENT = re.compile(r'^\s*("[^"]+"|[\w.\-]+)\s*(?:\[[^\]]*\])?\s*(\{.*)?$')
TREE_LINE = re.compile(r"^(?P<prefix>[\s│|]*)(?:├──|└──|\|--|`--|\+--)\s+(?P<name>\S+)")
MAX_TREE_LINES = 70


def body_sections(text):
    """{normalized ## heading: non-empty body lines}; fenced blocks count as content, `##` inside fences is not a heading."""
    secs, cur, in_fence = {}, None, False
    for l in text.splitlines():
        if FENCE_RE.match(l):
            in_fence = not in_fence
        if not in_fence and l.startswith("## "):
            cur = norm(l[3:])
            secs[cur] = []
        elif cur is not None and l.strip():
            secs[cur].append(l)
    return secs


def find_section(secs, raw):
    key = norm(raw)
    return next((v for k, v in secs.items() if k.startswith(key)), None)


def er_parse(src):
    """(entities, [(a, b, label)]) of a Mermaid erDiagram; quotes stripped, names lowercased."""
    ents, rels, depth = set(), [], 0
    unq = lambda x: x.strip('"').lower()
    for raw in src.splitlines():
        line = raw.strip()
        if not line or line.startswith("%%") or line.lower().startswith("erdiagram"):
            continue
        if depth > 0:
            depth += line.count("{") - line.count("}")
            continue
        m = ER_REL.match(line)
        if m:
            ents |= {unq(m.group(1)), unq(m.group(3))}
            rels.append((unq(m.group(1)), unq(m.group(3)), m.group(4)))
            continue
        m = ER_ENT.match(line)
        if m and not line.startswith(("direction", "style", "classDef", "class ")):
            ents.add(unq(m.group(1)))
            if m.group(2):
                depth = m.group(2).count("{") - m.group(2).count("}")
    return ents, rels


def tree_paths(block):
    """Reconstruct repo-relative paths from an ASCII tree; skips ellipsis lines."""
    stack, out = [], []
    for ln in block.splitlines():
        m = TREE_LINE.match(ln)
        if not m:
            continue
        depth = len(m.group("prefix").replace("\t", "    ")) // 4
        name = m.group("name")
        if "…" in name or name.startswith("..."):
            continue
        clean = name.rstrip("/").split("←")[0].split("#")[0].strip(",:")
        if not clean:
            continue
        stack = stack[:depth] + [clean]
        out.append("/".join(stack))
    return out


CMD_RE = re.compile(r"^\s*(?:\$\s*)?(npm|npx|pnpm|yarn|bun|pytest|python3?|pip3?|uv|poetry|php|composer|artisan|make|cargo|go|"
                    r"dotnet|mvn|\./mvnw|gradle|\./gradlew|alembic|flask|django-admin|bundle|rails|rake|node|deno|ruff|mypy|"
                    r"vitest|jest|playwright|prisma|sqlx|diesel)\b")
CWD_OK_RE = re.compile(r"\bcd\s+\S+|--prefix\b|\s-C\s|--directory\b|--project\b|--workdir\b|--cwd\b|"
                       r"\b(desde|from|in|en|em|dans)\s+`[^`]+/`|\((desde|from|en|in|em)\b|#\s*\S+/\s*$")
SHELL_LANGS = ("", "bash", "sh", "shell", "console", "zsh")
CONFIG_FILE_RE = re.compile(r"(^|/)(\.env(\.\w+)*\.(example|sample|dist)|config\.ya?ml|config\.toml|settings\.ya?ml|appsettings\.json)$")


def norm_marker(m):
    return re.sub(r"\s+", " ", m).strip().lower()


def marker_matches(needle, text_norm):
    """needle may be truncated with an ellipsis; compare the part before it."""
    n = norm_marker(needle)
    n = re.split(r"…|\.\.\.", n)[0].rstrip(" ]")
    return n in text_norm


def cwd_findings(doc, text, add, section_lines=None):
    """WARN for shell commands without an explicit working directory (multi-app repos only)."""
    lines = text.splitlines()
    if section_lines is not None:
        lines = section_lines
    in_fence, lang, cd_seen = False, "", False
    for i, line in enumerate(lines):
        fm = FENCE_RE.match(line)
        if fm:
            in_fence = not in_fence
            lang, cd_seen = fm.group(3).lower(), False
            continue
        ctx = " ".join(lines[max(0, i - 2):i + 1])
        cmds = []
        if in_fence:
            if lang in SHELL_LANGS:
                if re.match(r"\s*(\$\s*)?cd\s+\S+", line):
                    cd_seen = True
                elif CMD_RE.match(line):
                    cmds.append(line.strip())
        else:
            cmds = [m.group(1) for m in INLINE_RE.finditer(line) if CMD_RE.match(m.group(1))]
        for c in cmds:
            if not (cd_seen or CWD_OK_RE.search(c) or CWD_OK_RE.search(ctx)):
                add("WARN", doc, i + 1 if section_lines is None else 0,
                    f"Command without working directory (multi-app repo): `{c[:70]}` → prefix `cd <app> &&` or say «(desde `<app>/`)»")


def extra_checks(root, docs_dir, pack, meta, md_files, add, marker_re):
    """Cross-checks: coverage markers, quickstart, working directories, readability, operations, configuration."""
    modules_dir_f = pack["modules_dir"].rstrip("/") + "/"
    flows_dir_f = pack["flows_dir"].rstrip("/") + "/"
    def load(doc):
        with open(os.path.join(docs_dir, doc), encoding="utf-8", errors="ignore") as fh:
            return fh.read()

    try:
        import repo as repo_mod
        facts = repo_mod.analyze(root)
    except Exception as e:  # noqa: BLE001
        facts = None
        add("INFO", "-", 0, f"repository facts unavailable, operations/cwd checks skipped: {e}")
    multi_app = bool(facts) and facts["kind"] != "single-project"

    # A) coverage table markers <-> docs
    cov = pack.get("coverage_doc") or next((r for r in pack["required"] if r.startswith("_meta/") and r.endswith(".md")), None)
    if cov and cov in md_files:
        prose_by_doc = {d: "\n".join(l for _, l in split_md(load(d))[0]) for d in md_files}
        norm_by_doc = {d: norm_marker(t) for d, t in prose_by_doc.items()}
        cited = []
        for n, line in split_md(load(cov))[0]:
            if not line.lstrip().startswith("|") or re.match(r"^\s*\|[\s:|-]+\|\s*$", line):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            mk = next((m.group(0) for c in cells for m in [marker_re.search(c)] if m), None)
            if not mk:
                continue
            cited.append(mk)
            tok = next((t for c in cells for t in re.findall(r"[\w./-]+\.md\b", c)), None)
            if not tok:
                add("WARN", cov, n, f"Marker {mk[:50]} has no doc path in its row")
                continue
            tok = tok[2:] if tok.startswith("./") else tok
            target = tok if tok in md_files else next((d for d in md_files if d.endswith("/" + tok)), None)
            if not target:
                add("ERROR", cov, n, f"Marker {mk[:50]} cites a doc that does not exist: {tok}")
            elif not marker_matches(mk, norm_by_doc[target]):
                add("ERROR", cov, n, f"Marker {mk[:50]} is not in {target}: it was resolved or never written — fix the doc or the table")
        cited_norm = " ".join(norm_marker(c) for c in cited)
        for d in md_files:
            if d == cov:
                continue
            seen = set()
            for n, line in split_md(load(d))[0]:
                for m in marker_re.finditer(line):
                    key = norm_marker(m.group(0))
                    if key in seen:
                        continue
                    seen.add(key)
                    if not marker_matches(m.group(0), cited_norm):
                        add("WARN", d, n, f"Marker {m.group(0)[:50]} is not listed in {cov}")

    # B) README quickstart: 1-5 numbered steps
    rd, qs = pack.get("readme_doc"), pack.get("quickstart_section")
    if rd and qs and rd in md_files:
        body = find_section(body_sections(load(rd)), qs)
        if body is None:
            add("ERROR", rd, 0, f"Missing required section «## {qs}»: clean clone → first working result in ≤5 numbered steps")
        else:
            steps = [l for l in body if re.match(r"\s*\d+[.)]\s+", l)]
            if not steps:
                add("ERROR", rd, 0, f"«## {qs}» needs numbered steps (1. 2. 3. …)")
            elif len(steps) > 5:
                add("ERROR", rd, 0, f"«## {qs}» has {len(steps)} steps (max 5): link the rest to the environment doc")
            if not any("`" in l for l in body):
                add("WARN", rd, 0, f"«## {qs}» has no commands: give copy-pasteable ones")
            if multi_app:
                cwd_findings(rd, "", add, section_lines=body)

    # C) recipes: explicit working directory in multi-app repos
    rc = pack.get("recipes_doc")
    if rc and rc in md_files and multi_app:
        cwd_findings(rc, load(rc), add)

    # D) configuration section in the environment doc
    ed, cs = pack.get("env_doc"), pack.get("config_section")
    if facts and ed and cs and ed in md_files:
        files, _ = list_files(root)
        cfg = [f for f in files if CONFIG_FILE_RE.search(f)]
        if cfg and find_section(body_sections(load(ed)), cs) is None:
            add("WARN", ed, 0, f"Config files exist ({', '.join(cfg[:3])}) but «## {cs}» is missing: document how each is loaded and which values matter")

    # F) readability and single-source-of-truth for how-to
    rc_doc = pack.get("recipes_doc")
    crossref_re = re.compile(pack["crossref_re"], re.I) if pack.get("crossref_re") else None
    group_labels = {norm(g) for g in (pack.get("group_labels") or [])}
    link_re = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)\s]+)\)")
    for doc in md_files:
        if doc.startswith("_meta/"):
            continue
        text = load(doc)
        prose = split_md(text)[0]
        for n, line in prose:
            # F1) cross-reference written as prose instead of a link.
            #     A backticked target is a file outside the docs folder, which is cited as a path
            #     on purpose (a link leaving the folder breaks on wiki/site targets): leave it alone.
            if crossref_re:
                for m in crossref_re.finditer(line):
                    if "](" in line[max(0, m.start() - 2):m.end() + 2] or "`" in m.group(0):
                        continue
                    add("WARN", doc, n, f"Cross-reference {m.group(0)[:40]} is prose, not a link: "
                        "on a wiki the reader cannot follow it. Link the page")
            # F2) link text that does not describe its destination
            for m in link_re.finditer(line):
                label, target = norm(m.group(1)), m.group(2)
                if label in group_labels and re.search(r"/[^/)]+\.md$", target):
                    add("WARN", doc, n, f"Link «{m.group(1)}» points at one page ({target}) but reads like the whole group: "
                        "use the page's own name as the link text")
            # F3) sentences too long to scan
            if not line.lstrip().startswith(("|", ">", "#", "-", "*")) and not re.match(r"\s*\d+[.)]\s", line):
                for sentence in re.split(r"(?<=[.])\s+", line):
                    words = len(sentence.split())
                    if words > 45:
                        add("WARN", doc, n, f"Sentence of {words} words: split it, or turn the sequence into a numbered list")
        # F4) tables too wide for a wiki page
        for n, line in prose:
            if re.match(r"^\s*\|[\s:|-]+\|\s*$", line):
                cols = len([c for c in line.strip().strip("|").split("|") if c.strip()])
                if cols > 6:
                    add("WARN", doc, n, f"Table with {cols} columns: it overflows a wiki page. Split it, or fold "
                        "the path into the symbol cell")
        # F4b) a table whose only row says "nothing here": one sentence carries it without the grid
        lines = text.splitlines()
        for i, line in enumerate(lines):
            if not re.match(r"^\s*\|[\s:|-]+\|\s*$", line) or i == 0 or not lines[i - 1].lstrip().startswith("|"):
                continue
            rows = []
            for nxt in lines[i + 1:]:
                if not nxt.lstrip().startswith("|"):
                    break
                rows.append([c.strip() for c in nxt.strip().strip("|").split("|")])
            if len(rows) == 1 and len(rows[0]) >= 3:
                cells = rows[0]
                blank = sum(1 for c in cells if c.strip("`*_ ") in ("", "—", "–", "-", "n/a", "N/A"))
                if blank >= len(cells) / 2 or re.match(r"^\(.*\)$", cells[0]):
                    add("WARN", doc, i + 2, "Table with a single placeholder row: say it in one sentence "
                        "(what was searched, and that nothing was found) and drop the table")
        # F5) how-to steps written into a card or a flow instead of living in the recipes.
        #     Only the "how to modify"/"to change this flow" section counts: a flow's own
        #     "step by step" is the explanation of what happens, not a procedure to follow.
        if rc_doc:
            raw = (pack.get("howto_section") if doc.startswith(modules_dir_f)
                   else pack.get("flow_change_section") if doc.startswith(flows_dir_f) else None)
            if raw:
                body = find_section(body_sections(text), raw) or []
                steps = [l for l in body if re.match(r"\s*\d+[.)]\s+\S", l)]
                if len(steps) >= 3 and rc_doc.rsplit("/", 1)[-1] not in "\n".join(body):
                    add("WARN", doc, 0, f"«{raw}» carries {len(steps)} numbered steps and no link to {rc_doc}: "
                        "the procedure belongs in the recipes, once. Say where to start here and link it")

    # E) operations doc (Docker, data outside git, backups, observability) — required when there is evidence
    od, osec = pack.get("ops_doc"), pack.get("ops_sections")
    if not (facts and od and osec) or meta.get("operations") is False:
        return
    o = facts["operations"]
    ce = o["code_evidence"]
    docker_ev = bool(facts["compose_services"] or facts["dockerfiles"])
    skip = []
    for e in meta.get("operations_ignore") or []:
        if isinstance(e, dict) and e.get("path") and str(e.get("reason", "")).strip():
            skip.append(e["path"].rstrip("/"))
        else:
            add("WARN", "_meta/documake.json", 0, f"operations_ignore entry {e!r} needs {{\"path\": …, \"reason\": …}}: "
                "the reason is what tells the next reader why the folder is safe to ignore")
    silenced = lambda pth: any(pth.rstrip("/") == k or pth.rstrip("/").startswith(k + "/") for k in skip)
    ignored_mounts = [m for m in o["compose_mounts"] if m["git_ignored"] and not silenced(m["host"])]
    ignored_data = [i for i in (o["ignored_paths"] or []) if i["signal"] == "strong" and not silenced(i["path"])]
    weak_data = [i for i in (o["ignored_paths"] or []) if i["signal"] == "weak" and not silenced(i["path"])]
    need = (docker_ev or ignored_mounts or ignored_data or o["observability_services"]
            or any(ce[k] for k in ce) or meta.get("operations") is True)
    def weak_warn(doc, text):
        left = [i["path"] for i in weak_data if i["path"].rstrip("/").lower() not in text and
                os.path.basename(i["path"].rstrip("/")).lower() not in text]
        if left:
            add("WARN", doc, 0, f"{len(left)} git-ignored folder(s) with a generic name, undecided: {', '.join(left[:6])}. "
                "Evaluate each (who writes it? can it be rebuilt? does deleting it lose user/admin data?) then either describe it "
                f"under «## {osec[1]}» or list it in _meta/documake.json operations_ignore with a reason")

    if od not in md_files:
        weak_warn(rd or od, "")
        if need:
            add("ERROR", od, 0, "Operations evidence found (docker / persisted data / storage / backup / observability) but this doc is "
                'missing. Write it, or set "operations": false in _meta/documake.json with the reason in coverage')
        return
    secs = body_sections(load(od))
    for idx, raw in enumerate(osec):
        body = find_section(secs, raw)
        if body is None:
            if idx == 0 and not docker_ev:
                continue
            add("ERROR", od, 0, f"Missing required section «## {raw}»")
        elif not body:
            add("ERROR", od, 0, f"Section «## {raw}» is empty: state the finding, or say what was searched and found nothing (use an ASK marker if only a person knows)")
    data_text = " ".join(find_section(secs, osec[1]) or []).lower()
    weak_warn(od, data_text)
    reported = set()
    for path, why in [(m["host"], f"bind mount of service `{m['service']}`") for m in ignored_mounts] + \
                     [(i["path"], "git-ignored folder on disk") for i in ignored_data]:
        if path.rstrip("/") in reported:
            continue
        reported.add(path.rstrip("/"))
        if path.rstrip("/").lower() not in data_text and os.path.basename(path.rstrip("/")).lower() not in data_text:
            add("ERROR", od, 0, f"Data outside git not described under «## {osec[1]}»: `{path}` ({why}). "
                "Evaluate it first (who writes it? can it be rebuilt from git? would deleting it lose user data?). Not rebuildable → "
                "describe what it stores, who writes it and that it belongs in the backup. Rebuildable → say why it is disposable "
                "or add it to operations_ignore with a reason")



def special_checks(root, docs_dir, pack, meta, md_files, add):
    """Checks for the forced sections: stack+repo, abbreviated tree, database relations."""
    def load(doc):
        with open(os.path.join(docs_dir, doc), encoding="utf-8", errors="ignore") as fh:
            return fh.read()

    # 1) stack + repository doc
    sd = pack.get("stack_doc")
    if sd and sd in md_files:
        secs = body_sections(load(sd))
        for raw in pack["stack_sections"]:
            body = find_section(secs, raw)
            if body is None:
                add("ERROR", sd, 0, f"Missing required section «## {raw}»")
            elif not body:
                add("ERROR", sd, 0, f"Section «## {raw}» is empty: state the finding, or say what was searched and found nothing")
        try:
            import repo as repo_mod
            facts = repo_mod.analyze(root)
            links_body = " ".join(find_section(secs, pack["stack_sections"][-1]) or []).lower()
            for l in [l for l in facts["links"] if l["confidence"] == "declared" and not l["kind"].startswith("external")][:40]:
                tail = l["target"].split("→")[0].strip().rstrip("/").split("/")[-1].replace(".git", "").lower()
                if tail not in links_body and l["target"].lower() not in links_body:
                    add("WARN", sd, 0, f"Detected link to another repo is not mentioned in the relationship section: "
                        f"{l['kind']} → {l['target']} (evidence {l['evidence']})")
        except Exception as e:  # noqa: BLE001 - an extra check must never break the run
            add("INFO", sd, 0, f"link cross-check skipped: {e}")

    # 2) abbreviated structure
    st = pack.get("structure_doc")
    if st and st in md_files:
        _, blocks = split_md(load(st))
        trees = [b for b in blocks if "──" in b[1] or "|--" in b[1]]
        if not trees:
            add("ERROR", st, 0, "The structure doc needs an ASCII tree in a code block (├── / └──)")
        else:
            lines = [l for l in trees[0][1].splitlines() if l.strip()]
            if len(lines) > MAX_TREE_LINES:
                add("WARN", st, trees[0][2], f"Tree has {len(lines)} lines (> {MAX_TREE_LINES}): abbreviate it, collapse leaf dirs")
            for pth in tree_paths(trees[0][1]):
                if not os.path.exists(os.path.join(root, pth)):
                    add("ERROR", st, trees[0][2], f"Tree path does not exist: {pth}")

    # 3) database section
    dd = pack.get("data_doc")
    if not dd:
        return
    try:
        import schema as schema_mod
        sc = schema_mod.extract(root)
        an = schema_mod.analyze(sc)
    except Exception as e:  # noqa: BLE001
        add("INFO", "-", 0, f"schema cross-check skipped: {e}")
        return
    real = [t for t in sc.tables if t not in an["noise"]]
    flag = meta.get("database")
    need = flag is True or (flag is None and len(real) >= 3)
    if dd not in md_files:
        if need:
            add("ERROR", dd, 0, f"Database detected ({len(real)} tables from {', '.join(sorted(sc.sources))}) but this doc is missing. "
                f'Write it, or set "database": false in _meta/documake.json if the schema is not relevant')
        return
    if not real:
        add("WARN", dd, 0, "This doc exists but no tables were found in the code: check the entity names by hand")
        return
    text = load(dd)
    _, blocks = split_md(text)
    secs = body_sections(text)
    for raw in pack["data_sections"]:
        body = find_section(secs, raw)
        if body is None:
            add("ERROR", dd, 0, f"Missing required section «## {raw}»")
        elif not body:
            add("ERROR", dd, 0, f"Section «## {raw}» is empty")
    ers = [b for b in blocks if b[0] == "mermaid" and b[1].lstrip().lower().startswith("erdiagram")]
    if not ers:
        add("ERROR", dd, 0, "No Mermaid erDiagram found: show the core tables and their relations")
        return
    table_lc = {t.lower() for t in sc.tables}
    allowed = {frozenset((e["child"].lower(), e["parent"].lower())) for e in an["edges"] + an["logical_edges"]}
    for a in an["assoc"]:
        ps = [f["ref"].lower() for f in sc.tables[a]["fks"]]
        allowed |= {frozenset((ps[i], ps[j])) for i in range(len(ps)) for j in range(i + 1, len(ps))}
    words = [w.lower() for w in pack.get("logical_words", [])]
    drawn = set()
    for _, src, start in ers:
        ents, rels = er_parse(src)
        drawn |= ents
        if len(ents) > 12:
            add("WARN", dd, start, f"erDiagram has {len(ents)} entities (> 12): split by group, keep core tables only")
        for ent in sorted(ents):
            if ent not in table_lc:
                add("WARN", dd, start, f"Entity `{ent}` is not a table found in the code")
        for a, b, label in rels:
            if frozenset((a, b)) not in allowed and not any(w in label.lower() for w in words):
                add("WARN", dd, start, f"Relation {a} — {b} has no foreign key in the code. If it is a logical link, say so in the label")
    if len(real) >= 20 and len(drawn & {t.lower() for t in real}) >= 0.7 * len(real):
        add("WARN", dd, 0, f"Diagrams cover {len(drawn)} of {len(real)} tables: show only the core and groups; list the rest in a table")
    missing = [t for t in real if not re.search(r"(?<![\w])" + re.escape(t) + r"(?![\w])", text)]
    if missing:
        add("WARN", dd, 0, f"{len(missing)} table(s) not mentioned anywhere in this doc (list them in the last section, "
            f"one line each): {', '.join(missing[:10])}{' …' if len(missing) > 10 else ''}")



def check(root, docs_dir, lang_arg, use_mermaid):
    findings = []

    def add(level, doc, line, msg):
        findings.append({"level": level, "doc": doc, "line": line, "message": msg})

    if not os.path.isdir(docs_dir):
        add("ERROR", docs_dir, 0, "Docs folder does not exist")
        return None, findings

    lang, pack, missing, meta = load_pack(docs_dir, lang_arg)
    if missing:
        add("ERROR", "_meta/documake.json", 0,
            f"Language '{lang}' has no built-in pack; declare 'structure' with: {', '.join(missing)}")
        return lang, findings
    builder_re = re.compile("|".join(pack["phrases"]), re.I) if pack.get("phrases") else None
    if not builder_re:
        add("WARN", "-", 0, f"No builder-phrase list for '{lang}': review perspective manually")
    markers = pack.get("markers") or LANG_PACKS["es"]["markers"] + LANG_PACKS["en"]["markers"]
    marker_re = re.compile(r"\[(" + "|".join(re.escape(m) for m in markers) + r")\b[^\]]*\]")
    modules_dir, flows_dir = pack["modules_dir"].rstrip("/") + "/", pack["flows_dir"].rstrip("/") + "/"
    sections = [norm(s) for s in pack["module_sections"]]

    md_files = []
    for dp, _, fns in os.walk(docs_dir):
        for fn in fns:
            if fn.endswith(".md"):
                md_files.append(os.path.relpath(os.path.join(dp, fn), docs_dir))
    md_files.sort()

    for req in pack["required"]:
        if req not in md_files:
            add("ERROR", req, 0, "Required document missing")
    td = pack.get("tutorial_doc")
    if td and td not in md_files and meta.get("tutorial") is not False:
        add("ERROR", td, 0, "No first-change tutorial: reference and explanation without a way in. Write it and run "
            'its steps, or set "tutorial": false in _meta/documake.json with the reason in coverage')
    if not any(f.startswith(modules_dir) for f in md_files):
        add("ERROR", modules_dir, 0, "No module cards")
    if not any(f.startswith(flows_dir) for f in md_files):
        add("WARN", flows_dir, 0, "No flows documented")

    paths, dirs, idents, corpus = build_index(root, docs_dir)
    mmdc = shutil.which("mmdc") if use_mermaid else None
    if use_mermaid and not mmdc:
        add("WARN", "-", 0, "--mermaid requested but mmdc not installed (npm i -g @mermaid-js/mermaid-cli)")

    for doc in md_files:
        full = os.path.join(docs_dir, doc)
        with open(full, encoding="utf-8", errors="ignore") as fh:
            text = fh.read()
        prose, blocks = split_md(text)
        is_meta = doc.startswith("_meta/")

        for n, line in prose:
            no_code = INLINE_RE.sub("", line)
            for m in LINE_REF_RE.finditer(line):
                add("ERROR", doc, n, f"Line-number reference «{m.group(0)}»: use path + symbol")
            if builder_re and not is_meta and not line.lstrip().startswith("#"):
                for m in builder_re.finditer(no_code):
                    add("WARN", doc, n, f"Builder perspective «{m.group(0)}» → {line.strip()[:90]}")
            for m in marker_re.finditer(line):
                add("INFO", doc, n, m.group(0))
            for m in LINK_RE.finditer(line):
                if "#" in m.group(1) and not re.match(r"^[a-z]+:", m.group(1)):
                    add("WARN", doc, n, f"Anchor link {m.group(1)}: slugs differ between GitLab, Zensical/MkDocs "
                        "and Docsify (accents!). Link the file and name the section in the text")
                target = m.group(1).split("#")[0]
                if not target or re.match(r"^[a-z]+:", target):
                    continue
                resolved = os.path.normpath(os.path.join(os.path.dirname(full), target))
                if not os.path.exists(resolved):
                    add("ERROR", doc, n, f"Broken link: {m.group(1)}")
                elif os.path.relpath(resolved, docs_dir).startswith(".."):
                    add("WARN", doc, n, f"Link leaves the docs folder ({m.group(1)}): it breaks on wiki/site targets. "
                        "Cite the file as a backticked path instead")
            for m in INLINE_RE.finditer(line):
                kind, tok = classify(m.group(1))
                if kind == "path":
                    p = tok[2:] if tok.startswith("./") else tok
                    p = p.rstrip("/")
                    if p not in paths and p not in dirs and not os.path.exists(os.path.join(root, p)) and p not in corpus:
                        add("ERROR", doc, n, f"Path does not exist: `{tok}`")
                elif kind == "symbol":
                    parts = [s.strip() for s in re.split(r"\.|::|#|->", tok) if s.strip()]
                    absent = [s for s in parts if s not in idents]
                    if absent:
                        add("WARN", doc, n, f"Symbol not found in code: `{tok}` (missing: {', '.join(absent)})")

        for blang, src, start in blocks:
            if blang != "mermaid":
                continue
            first = next((l.strip() for l in src.splitlines() if l.strip() and not l.strip().startswith("%%")), "")
            if not first:
                add("ERROR", doc, start, "Empty mermaid block")
                continue
            if not first.split()[0].lower().startswith(MERMAID_TYPES):
                add("ERROR", doc, start, f"Mermaid without a known diagram type: «{first[:40]}»")
                continue
            count = mermaid_nodes(src)
            if count > 12:
                add("WARN", doc, start, f"Diagram has ~{count} nodes (max 12): split it")
            if mmdc:
                with tempfile.TemporaryDirectory() as td:
                    inp, out = os.path.join(td, "d.mmd"), os.path.join(td, "d.svg")
                    open(inp, "w", encoding="utf-8").write(src)
                    r = subprocess.run([mmdc, "-i", inp, "-o", out, "-q"], capture_output=True, text=True)
                    if r.returncode != 0:
                        err = (r.stderr or r.stdout).strip().splitlines()
                        add("ERROR", doc, start, "Mermaid does not compile: " + (err[-1] if err else "unknown error"))

        if doc.startswith(modules_dir):
            heads = [norm(l[3:]) for _, l in prose if l.startswith("## ")]
            for sec, raw in zip(sections, pack["module_sections"]):
                if not any(h.startswith(sec) for h in heads):
                    add("ERROR", doc, 0, f"Module card missing required section «## {raw}»")

    extra_checks(root, docs_dir, pack, meta, md_files, add, marker_re)
    special_checks(root, docs_dir, pack, meta, md_files, add)
    return lang, findings


def audit(root, files):
    """Backticked paths in pre-existing docs that exist nowhere in the repo (drift)."""
    paths, dirs, _, corpus = build_index(root, os.path.join(root, "\0none"))
    everything = paths | dirs
    out = []
    for rel in files:
        full = rel if os.path.isabs(rel) else os.path.join(root, rel)
        try:
            text = open(full, encoding="utf-8", errors="ignore").read()
        except OSError:
            out.append((rel, 0, f"cannot read {rel}"))
            continue
        prose, _ = split_md(text)
        seen = set()
        for n, line in prose:
            for m in INLINE_RE.finditer(line):
                kind, tok = classify(m.group(1))
                if kind != "path" or tok in seen:
                    continue
                seen.add(tok)
                p = (tok[2:] if tok.startswith("./") else tok).rstrip("/")
                here = os.path.normpath(os.path.join(os.path.dirname(os.path.relpath(full, root)), p))
                if (p in everything or here in everything or p in corpus
                        or os.path.exists(os.path.join(root, p)) or any(e.endswith("/" + p) for e in everything)):
                    continue
                out.append((rel, n, f"`{tok}` exists nowhere in the repo"))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--docs", default=None, help="docs folder (default <root>/docs)")
    ap.add_argument("--lang", default=None, help="docs language (default: documake.json, else es)")
    ap.add_argument("--mermaid", action="store_true", help="compile diagrams with mmdc")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--audit", nargs="+", metavar="FILE", help="report drift in pre-existing docs and exit")
    a = ap.parse_args()
    root = os.path.abspath(a.root)
    if a.audit:
        drift = audit(root, a.audit)
        for rel, n, msg in drift:
            print(f"[DRIFT] {rel}:{n} — {msg}")
        print(f"\n{len(drift)} stale references (candidates for the pitfalls doc; never copy them)")
        sys.exit(0)
    docs = a.docs if a.docs and os.path.isabs(a.docs) else os.path.join(root, a.docs or "docs")
    lang, f = check(root, docs, a.lang, a.mermaid)
    order = {"ERROR": 0, "WARN": 1, "INFO": 2}
    f.sort(key=lambda x: (order[x["level"]], x["doc"], x["line"]))
    counts = {k: sum(1 for x in f if x["level"] == k) for k in order}
    if a.json:
        json.dump({"language": lang, "summary": counts, "findings": f}, sys.stdout, ensure_ascii=False, indent=2)
        print()
    else:
        for x in f:
            loc = f"{x['doc']}:{x['line']}" if x["line"] else x["doc"]
            print(f"[{x['level']}] {loc} — {x['message']}")
        print(f"\nLanguage: {lang} · {counts['ERROR']} errors · {counts['WARN']} warnings · {counts['INFO']} markers")
        print("CLEAN" if counts["ERROR"] == 0 else "ERRORS: fix and re-run")
    sys.exit(1 if counts["ERROR"] else 0)


if __name__ == "__main__":
    main()
